name: "Deploy to GitHub Pages"

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  export:
    name: Export to HTML5
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/4.2.2.stable ~/.local/share/godot/export_templates/4.2.2.stable

      - name: Export Web
        run: |
          mkdir -v -p build/web
          godot --headless --export-release "Web" build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: pages
