name: "Deploy to GitHub Pages"

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  export:
    name: Export to HTML5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Godot files
        id: cache-godot
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/godot/**
            ~/.local/bin/godot
            ~/.config/godot/**
          key: ${{ runner.os }}-godot-4.8-dev3

      - name: Download and config Godot Engine linux server and templates
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/godotengine/godot-builds/releases/download/4.8-dev3/Godot_v4.8-dev3_linux.x86_64.zip
          wget -q https://github.com/godotengine/godot-builds/releases/download/4.8-dev3/Godot_v4.8-dev3_export_templates.tpz
          unzip Godot_v4.8-dev3_linux.x86_64.zip
          unzip Godot_v4.8-dev3_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.8.dev3.official
          mkdir -p ~/.config/godot/
          mkdir -p ~/.local/bin/
          mv templates/* ~/.local/share/godot/export_templates/4.8.dev3.official
          rm -f Godot_v4.8-dev3_linux.x86_64.zip Godot_v4.8-dev3_export_templates.tpz
          mv ./Godot_v4.8-dev3_linux.x86_64 ~/.local/bin/godot

      - name: Export Web
        run: |
          mkdir -v -p build/web
          ~/.local/bin/godot --headless --export-release "Web" build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: pages
